app/models.py
import re
from sqlalchemy.orm import backref, lazyload
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

class User(UserMixin,db.Model):
    """Class that defines a User Model and helps us create new users."""
    __tablename__ = "users"
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique=True,index=True)
    user_password = db.Column(db.String(255))
    pitches = db.relationship("Pitch",backref="user",lazy="dynamic")
    comments = db.relationship("Comment", backref="user",lazy="dynamic")
    categories = db.relationship("Category", backref="user",lazy="dynamic")

    @property
    def password(self):
        """Defines a write only class property password"""
        raise AttributeError("You cannot read the password attribute")

    @password.setter
    def password(self, password):
        """Method that takes in a password and hashes it."""
        self.user_password = generate_password_hash(password)


    def password_verification(self,password):
        """Method that checks whether a hashed password and user password that it hashes match."""
        return check_password_hash(self.user_password,password)
    
    def get_user_id(self):
        return self.id

    def __repr__(self):
        return f'User {self.username}'
    
@login_manager.user_loader
def loads_user(user_id):
    """Method that queries the datbase and gets a user with the passed id."""
    return User.query.get(int(user_id))  

class Pitch(db.Model):
    """Class that defines a Pitch Model and creates new pitches."""
    __tablename__ = "pitches"
    id = id = db.Column(db.Integer,primary_key = True)
    user_pitch = db.Column(db.String(800))
    time_posted = db.Column(db.DateTime,default=datetime.now)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    category_id = db.Column(db.Integer,db.ForeignKey("categories.id"))
    comments = db.relationship("Comment",backref="pitch",lazy="dynamic")

    
    def save_pitch(self):
        db.session.add(self)
        db.session.commit()
        
    @classmethod
    def get_user_pitches(cls,id):
        """Returns all a user's pitches."""
        user_pitches = Pitch.query.filter_by(user_id=id).all()
        return user_pitches
    @classmethod
    def get_all_pitches(cls):
        """Returns all pitches."""
        pitches = Pitch.query.all()
        return pitches  

    
class Category(db.Model):
    """Creates category instances and defines category methods.""" 
    __tablename__="categories"
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    pitches = db.relationship("Pitch",backref="category",lazy="dynamic")

    def save_category(self):
        db.session.add(self)
        db.session.commit()
    
    @classmethod
    def get_categories(cls):
        """Returns all categories."""
        categories = Category.query.all()
        return categories 
    
class Comment(db.Model):
    """Class that defines a Pitch Model and creates new pitches."""
    __tablename__ = "comments"
    id = id = db.Column(db.Integer,primary_key = True)
    author=db.Column(db.String(100))
    comment = db.Column(db.String)
    time_posted = db.Column(db.DateTime,default=datetime.now)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    pitch_id = db.Column(db.Integer,db.ForeignKey("pitches.id"))
    
    def save_comment(self):
        db.session.add(self)
        db.session.commit()
        
    @classmethod
    def get_pitch_comments(cls,id):
        """Returns all a pitch's comments."""
        pitch_comments = Comment.query.filter_by(pitch_id=id).all()
        return pitch_comments
    


    

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,ValidationError
from wtforms.validators import Required

class PitchForm(FlaskForm):

    name = StringField('Input Name',validators=[Required()])
    pitch = TextAreaField('Write your Pitch: ')
    submit = SubmitField('Submit Pitch')
    
class CommentForm(FlaskForm):

    author = StringField('Input Name',validators=[Required()])
    pitch = TextAreaField('Add a Comment: ')
    submit = SubmitField('Submit Comment')

    

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from flask_simplemde import SimpleMDE

bootsrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
mail = Mail()
simple = SimpleMDE()

login_manager.session_protection="strong"
login_manager.login_view="authentication.login"

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config_options[config_name])
    
    #Initializing flask extensions
    bootsrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)
    #Registering blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import authentication as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix="/authentication")
    
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..models import Comment, User,Category,Pitch
from flask_login import login_required,current_user
from .forms import PitchForm,CommentForm
import markdown2

@main.route("/")
def index():
    """View root page function that returns the index page and its data"""
    pitches = Pitch.get_all_pitches()
    name= PitchForm.name
    title="1Minute App"
    return render_template("index.html",title=title,pitches=pitches,name=name)

@main.route('/user/<username>')
def my_profile(username):
    "Show user profile."
    user = User.query.filter_by(username = username).first()
    user_pitches= Pitch.get_user_pitches(user.id)

    if user is None:
        abort(404)
    title="Profile Page"
    return render_template("profile/user_profile.html", user=user,title=title,user_pitches=user_pitches)

@main.route("/categories")
def categories():
    """View function that returns the categories page andshows the available categories"""
    categories = Category.get_categories()
    title="Pitch Categories"
    return render_template("categories.html",categories=categories, title=title)

@main.route('/categories/pitch/new/<name>', methods = ['GET','POST'])
@login_required
def new_pitch(name):

    pitch_form = PitchForm()
    category = Category

    if pitch_form.validate_on_submit():
        name = pitch_form.name.data
        pitch = pitch_form.pitch.data
        new_pitch = Pitch(user_pitch=pitch,user=current_user)
        new_pitch.save_pitch()
        return redirect(url_for('.index'))

    title = "New Pitch"
    return render_template('new_pitch.html',title = title, pitch_form=pitch_form,name=name, category=category)

@main.route("/pitch/<int:id>")
def single_pitch(id):
    pitch=Pitch.query.get(id)
    comments = Comment.get_pitch_comments(pitch.id)
    if pitch is None:
        abort(404)
    format_pitch = markdown2.markdown(pitch.user_pitch,extras=["code-friendly", "fenced-code-blocks"])
    return render_template('pitch.html',pitch=pitch,format_pitch=format_pitch,comments=comments)

@main.route('/pitch/comment/new/<int:id>', methods = ['GET','POST'])
@login_required
def new_comment(id):

    comment_form= CommentForm()
    pitch = Pitch.query.get(id)

    if comment_form.validate_on_submit():
        author = comment_form.author.data
        pitch_comment = comment_form.pitch.data
        new_comment = Comment(author=author,comment=pitch_comment,user=current_user,pitch_id=pitch.id)
        new_comment.save_comment()
        return redirect(url_for('.single_pitch',id=pitch.id))

    title = "New Comment"
    return render_template('new_comment.html',title = title, comment_form=comment_form)

app/templates/base.html
{% extends 'bootstrap/base.html'%}
{%block styles %}
    {{super()}}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" rel="stylesheet" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
    {{ simplemde.css}}
    {{ simplemde.js }}
{% endblock %}

{% block navbar %}
    {% include "navbar.html" %}
{% endblock %}

app/templates/categories.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/categories.css')}}">
{% endblock %}
{% block content %}
    <div class="container">
        {{macro.displayCategories(categories)}}
    </div>
{% endblock %}

app/templates/index.html
{%extends "base.html"%}
{% import 'macros.html' as macro%}
{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}


{%block content%}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-1"></div>
            <div class="col-md-10">
                <h1 >1Minute Pitch</h1>
                <div class="btn">
                    <a href="/categories" class="main-link-btn">Add New Pitch</a>
                </div>

            </div>
            <div class="col-md-1"></div>
    </div>
    {{macro.displayPitches(pitches)}}
</div>
{%endblock%}

app/templates/macros.html
{% macro displayCategories(categories_list) %}
    {% for category in categories_list %}
        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-10 ">
                <div class="card text-center">
                    <div class="card-body">
                        <h2>{{category.name|title}}</h2>
                        <a href="/categories/pitch/new/{{category.name}}" class="link-btn">Create Pitch</a>
                    </div>
                </div>            
            </div>
            <div class="col-md-1"></div>
        </div>
    {% endfor %}
{% endmacro %}
{% macro displayPitches(pitches_list) %}
    {% for pitch in pitches_list%}
        <div class="row">
            <div class="col-md-1 "></div>
            <div class="col-md-10 ">
                <div class="card text-center">
                    <h2>Pitch: </h2>
                    <h3>{{pitch.user_pitch|truncate}}</h3>
                    <h2>Submitted at: </h2>
                    <h3>{{pitch.time_posted}}</h3>
                    <div class="card-btn">
                        <a href="{{url_for('main.single_pitch',id=pitch.id)}}" class="link-btn">View Pitch</a>
                    </div>
                </div>            
            </div>
            <div class="col-md-1"></div>
        </div>
    {% endfor %}
{% endmacro %}
{% macro displayComments(comments_list) %}
    {% for comment in comments_list%}
        <div class="row">
            <div class="col-md-1 "></div>
            <div class="col-md-10 ">
                <div class="card text-center">
                    <div class="card-body">
                        <h2>Author: </h2>
                        <h3>{{comment.author}}</h3>
                        <h2>Comment: </h2>
                        <h3>{{comment.comment}}</h3>
                        <h2>Submitted at: </h2>
                        <h3>{{comment.time_posted}}</h3>
                    </div>
                </div>            
            </div>
            <div class="col-md-1"></div>
        </div>
    {% endfor %}
{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">1Minute Pitch</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li><a href="{{url_for('main.my_profile',username=current_user.username)}}">Profile</a></li>
            <li style="color:white;padding:15px;">{{current_user.username}}</li>
            <li><a href="{{url_for('authentication.logout')}}">Sign out</a></li>
            {% else %}
            <li><a href="{{url_for('authentication.login')}}">Sign in</a></li>
            {%endif%}
          </ul>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <li><a href="/categories">Categories</a></li>
        </div>

    </div>
</div>

app/templates/new_comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container">

        <div class="col-md-2"></div>

        <div class="col-md-8">

            {{ wtf.quick_form(comment_form) }}
            {{simplemde.load}}
        </div>
        <div class="col-md-2"></div>


    </div>

{% endblock %}

app/templates/new_pitch.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container">

        <div class="col-md-2"></div>

        <div class="col-md-8">

            {{ wtf.quick_form(pitch_form) }}
            {{simplemde.load}}
        </div>
        <div class="col-md-2"></div>


    </div>

{% endblock %}

app/templates/pitch.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/pitch.css')}}">
{% endblock %}
{% block content%}
<div class="row">
    <div class="col-md-1 "></div>
    <div class="col-md-10 ">
        <div class="card text-center">
            <h2>Pitch: </h2>
            <h3>{{format_pitch|safe}}</h3>
            <h2>Submitted at: </h2>
            <h3>{{pitch.time_posted}}</h3>
            <a href="/pitch/comment/new/{{pitch.id}}" class="link-btn">Add Comment</a>
        </div>            
    </div>
    <div class="col-md-1"></div>
    <div class="row">
        <hr>
        <h1>Comments: </h1>
        <hr>
        {% if comments %}
            {% for comment in comments%}
            <div class="row">
                <div class="col-md-1 "></div>
                <div class="col-md-10 ">
                    <div class="card text-center" id="comment">
                        <div class="card-body">
                            <h2>Author: </h2>
                            <h3>{{comment.author}}</h3>
                            <h2>Comment: </h2>
                            <h3>{{comment.comment}}</h3>
                            <h2>Submitted at: </h2>
                            <h3>{{comment.time_posted}}</h3>
                        </div>
                    </div>            
                </div>
                <div class="col-md-1"></div>
            </div>
            {% endfor %}        
        {% else%}
            <h1 class="text-center">This Pitch has no comments!</h3>
        {% endif %}
    </div>

</div>
{%endblock%}

app/templates/profile/user_profile.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/profile.css')}}">
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <h1 style="text-align: center;">{{user.username|capitalize}}'s PROFILE PAGE</h1><br>
            {{macro.displayPitches(user_pitches)}}
        </div>
        <div class="col-md-1"></div>
    </div>
</div>
{% endblock %}